language: python
python:
  - 2.7
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - sudo apt-get install gfortran
install:
  - pip install --upgrade pip setuptools wheel numpy cython
  - pip install --no-cache-dir -U -r requirements.txt | cat
script:
  - pytest -v --cov=stheno --cov-report term-missing
after_success:
  - coveralls